# Generated by Django 5.0.4 on 2024-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
