# Generated by Django 5.0.4 on 2024-05-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_coupon_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
