# Generated by Django 5.0.4 on 2024-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_valid_from_remove_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
