# Generated by Django 5.0.4 on 2024-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupons_coupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
