# Generated by Django 5.0.4 on 2024-06-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupons_coupon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='coupon_name',
        ),
    ]
