# Generated by Django 5.0.4 on 2024-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_remove_coupons_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupon_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
