# Generated by Django 5.0.4 on 2024-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_offer',
            field=models.FloatField(default=0),
        ),
    ]
