# Generated by Django 5.0.4 on 2024-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_offer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
