# Generated by Django 5.0.4 on 2024-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(max_length=100),
        ),
    ]
