# Generated by Django 5.0.4 on 2024-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
