# Generated by Django 5.0.4 on 2024-05-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon_valid_from_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupons',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
